import {weatherForecastApiSchema} from "@/schemas/WeatherAPISchemas/weatherForecastApiSchema.ts";
import {searchLocationApiSchema} from "@/schemas/WeatherAPISchemas/searchLocationApiSchema.ts";
import {currentWeatherApiSchema} from "@/schemas/WeatherAPISchemas/currentWeatherApiSchema.ts";

const WEATHER_API_KEY = import.meta.env.VITE_WEATHER_API_KEY

type CurrentWeatherArgsType = {
    lat: number
    lng: number
    aqi?: "yes" | "no"

}

export async function getCurrentWeatherData({lat, lng, aqi}: CurrentWeatherArgsType) {


    try {

        if (!lat || !lng) {
            throw new Error("No location found.");
        }

        // return {
        //     "location": {
        //         "name": "Garhi Brahmanan",
        //         "region": "Haryana",
        //         "country": "India",
        //         "lat": 28.996,
        //         "lon": 76.996,
        //         "tz_id": "Asia/Kolkata",
        //         "localtime_epoch": 1783623692,
        //         "localtime": "2026-07-10 00:31"
        //     },
        //     "current": {
        //         "last_updated_epoch": 1783622700,
        //         "last_updated": "2026-07-10 00:15",
        //         "temp_c": 25.0,
        //         "temp_f": 77.0,
        //         "is_day": 0,
        //         "condition": {
        //             "text": "Partly Cloudy",
        //             "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
        //             "code": 1003
        //         },
        //         "wind_mph": 6.0,
        //         "wind_kph": 9.7,
        //         "wind_degree": 31,
        //         "wind_dir": "NNE",
        //         "pressure_mb": 999.0,
        //         "pressure_in": 29.49,
        //         "precip_mm": 0.0,
        //         "precip_in": 0.0,
        //         "humidity": 89,
        //         "cloud": 58,
        //         "feelslike_c": 19.1,
        //         "feelslike_f": 66.4,
        //         "windchill_c": 25.0,
        //         "windchill_f": 77.0,
        //         "heatindex_c": 27.7,
        //         "heatindex_f": 81.8,
        //         "dewpoint_c": 23.0,
        //         "dewpoint_f": 73.4,
        //         "vis_km": 10.0,
        //         "vis_miles": 6.0,
        //         "uv": 0.0,
        //         "gust_mph": 8.5,
        //         "gust_kph": 13.7,
        //         "will_it_rain": 0,
        //         "chance_of_rain": 19,
        //         "will_it_snow": 0,
        //         "chance_of_snow": 0,
        //         "wetbulb_c": 0.0,
        //         "wetbulb_f": 32.0,
        //         "short_rad": 0,
        //         "diff_rad": 0,
        //         "dni": 0,
        //         "gti": 0
        //     }
        // }

        const result = await fetch(
            "https://api.weatherapi.com/v1/current.json?" +
            `q=${lat},${lng}&` +
            `aqi=${aqi || "no"}&` +
            `key=${WEATHER_API_KEY}`
        )
        const rawData = await result.json();

        // Validates the structural footprint safely
        const validation = currentWeatherApiSchema.safeParse(rawData);

        if (!validation.success) {
            console.error("API Schema changed or is invalid:", validation.error);
            return []; // Return fallback safe state
        }

        // Success! TypeScript now recognizes this a currentWeatherApiSchema
        const validatedData = validation.data;
        return validatedData;

    } catch (error) {
        console.error("Network or parsing error:", error);
        return [];
    }
}



type ForecastArgsType = {
    lat: number
    lng: number
    aqi?: "yes" | "no"
    days?: number | undefined
    timePeriod?: number | undefined
}

export async function getForecastData({lat, lng, aqi, days, timePeriod}: ForecastArgsType) {


    try {
        if (!lat || !lng) {
            throw new Error("No location found.");
        }
        await new Promise(r => setTimeout(r, 2000));
        // return {
        //     "location":{
        //         "name":"Garhi Brahmanan",
        //         "region":"Haryana",
        //         "country":"India",
        //         "lat":28.996,
        //         "lon":76.996,
        //         "tz_id":"Asia/Kolkata",
        //         "localtime_epoch":1783412276,
        //         "localtime":"2026-07-07 13:47"
        //     },
        //     "current":{
        //         "last_updated_epoch":1783412100,
        //         "last_updated":"2026-07-07 13:45",
        //         "temp_c":35.1,
        //         "temp_f":95.2,
        //         "is_day":1,
        //         "condition":{
        //             "text":"Moderate or heavy rain with thunder",
        //             "icon":"//cdn.weatherapi.com/weather/64x64/day/389.png",
        //             "code":1276
        //         },
        //         "wind_mph":5.6,
        //         "wind_kph":9.0,
        //         "wind_degree":232,
        //         "wind_dir":"SW",
        //         "pressure_mb":999.0,
        //         "pressure_in":29.5,
        //         "precip_mm":0.0,
        //         "precip_in":0.0,
        //         "humidity":56,
        //         "cloud":75,
        //         "feelslike_c":37.2,
        //         "feelslike_f":99.0,
        //         "windchill_c":38.0,
        //         "windchill_f":100.5,
        //         "heatindex_c":42.9,
        //         "heatindex_f":109.2,
        //         "dewpoint_c":20.7,
        //         "dewpoint_f":69.2,
        //         "vis_km":4.0,
        //         "vis_miles":2.0,
        //         "uv":2.7,
        //         "gust_mph":6.4,
        //         "gust_kph":10.4,
        //         "will_it_rain":0,
        //         "chance_of_rain":3,
        //         "will_it_snow":0,
        //         "chance_of_snow":0,
        //         "wetbulb_c":25.5,
        //         "wetbulb_f":77.9,
        //         "short_rad":625.14,
        //         "diff_rad":212.99,
        //         "dni":0.0,
        //         "gti":0.0
        //     },
        //     "forecast":{
        //         "forecastday":[
        //             {
        //                 "date":"2026-07-07",
        //                 "date_epoch":1783382400,
        //                 "day":{
        //                     "maxtemp_c":38.2,
        //                     "maxtemp_f":100.7,
        //                     "mintemp_c":31.4,
        //                     "mintemp_f":88.6,
        //                     "avgtemp_c":34.8,
        //                     "avgtemp_f":94.7,
        //                     "maxwind_mph":8.5,
        //                     "maxwind_kph":13.7,
        //                     "totalprecip_mm":0.02,
        //                     "totalprecip_in":0.0,
        //                     "totalsnow_cm":0.0,
        //                     "avgvis_km":10.0,
        //                     "avgvis_miles":6.0,
        //                     "avghumidity":45,
        //                     "daily_will_it_rain":0,
        //                     "daily_chance_of_rain":5,
        //                     "daily_will_it_snow":0,
        //                     "daily_chance_of_snow":0,
        //                     "condition":{
        //                         "text":"Partly Cloudy",
        //                         "icon":"//cdn.weatherapi.com/weather/64x64/day/116.png",
        //                         "code":1003
        //                     },
        //                     "uv":5.3,
        //                     "avgwetbulb_c":24.8,
        //                     "avgwetbulb_f":76.7,
        //                     "maxwetbulb_c":25.6,
        //                     "maxwetbulb_f":78.0
        //                 },
        //                 "astro":{
        //                     "sunrise":"05:29 AM",
        //                     "sunset":"07:24 PM",
        //                     "moonrise":"11:47 PM",
        //                     "moonset":"12:00 PM",
        //                     "moon_phase":"Last Quarter",
        //                     "moon_illumination":39,
        //                     "is_moon_up":0,
        //                     "is_sun_up":1
        //                 },
        //                 "hour":[
        //                     {
        //                         "time_epoch":1783362600,
        //                         "time":"2026-07-07 00:00",
        //                         "temp_c":32.7,
        //                         "temp_f":90.8,
        //                         "is_day":0,
        //                         "condition":{
        //                             "text":"Clear",
        //                             "icon":"//cdn.weatherapi.com/weather/64x64/night/113.png",
        //                             "code":1000
        //                         },
        //                         "wind_mph":6.3,
        //                         "wind_kph":10.1,
        //                         "wind_degree":88,
        //                         "wind_dir":"E",
        //                         "pressure_mb":998.0,
        //                         "pressure_in":29.46,
        //                         "precip_mm":0.0,
        //                         "precip_in":0.0,
        //                         "snow_cm":0.0,
        //                         "humidity":50,
        //                         "cloud":13,
        //                         "feelslike_c":35.6,
        //                         "feelslike_f":96.1,
        //                         "windchill_c":32.7,
        //                         "windchill_f":90.8,
        //                         "heatindex_c":36.1,
        //                         "heatindex_f":97.1,
        //                         "dewpoint_c":20.9,
        //                         "dewpoint_f":69.6,
        //                         "will_it_rain":0,
        //                         "chance_of_rain":2,
        //                         "will_it_snow":0,
        //                         "chance_of_snow":0,
        //                         "vis_km":10.0,
        //                         "vis_miles":6.0,
        //                         "gust_mph":9.2,
        //                         "gust_kph":14.8,
        //                         "uv":0,
        //                         "wetbulb_c":24.2,
        //                         "wetbulb_f":75.6,
        //                         "short_rad":0,
        //                         "diff_rad":0,
        //                         "dni":0,
        //                         "gti":0
        //                     },
        //                     {
        //                         "time_epoch":1783366200,
        //                         "time":"2026-07-07 01:00",
        //                         "temp_c":32.4,
        //                         "temp_f":90.4,
        //                         "is_day":0,
        //                         "condition":{
        //                             "text":"Smoky haze",
        //                             "icon":"//cdn.weatherapi.com/weather/64x64/night/149.png",
        //                             "code":1036
        //                         },
        //                         "wind_mph":6.3,
        //                         "wind_kph":10.1,
        //                         "wind_degree":98,
        //                         "wind_dir":"E",
        //                         "pressure_mb":997.0,
        //                         "pressure_in":29.45,
        //                         "precip_mm":0.0,
        //                         "precip_in":0.0,
        //                         "snow_cm":0.0,
        //                         "humidity":49,
        //                         "cloud":20,
        //                         "feelslike_c":34.9,
        //                         "feelslike_f":94.8,
        //                         "windchill_c":32.4,
        //                         "windchill_f":90.4,
        //                         "heatindex_c":35.5,
        //                         "heatindex_f":95.9,
        //                         "dewpoint_c":20.4,
        //                         "dewpoint_f":68.7,
        //                         "will_it_rain":0,
        //                         "chance_of_rain":2,
        //                         "will_it_snow":0,
        //                         "chance_of_snow":0,
        //                         "vis_km":9.7,
        //                         "vis_miles":6.0,
        //                         "gust_mph":9.6,
        //                         "gust_kph":15.4,
        //                         "uv":0,
        //                         "wetbulb_c":23.9,
        //                         "wetbulb_f":75.0,
        //                         "short_rad":0,
        //                         "diff_rad":0,
        //                         "dni":0,
        //                         "gti":0
        //                     },
        //                     {
        //                         "time_epoch":1783369800,
        //                         "time":"2026-07-07 02:00",
        //                         "temp_c":31.8,
        //                         "temp_f":89.2,
        //                         "is_day":0,
        //                         "condition":{
        //                             "text":"Smoky haze",
        //                             "icon":"//cdn.weatherapi.com/weather/64x64/night/149.png",
        //                             "code":1036
        //                         },
        //                         "wind_mph":6.0,
        //                         "wind_kph":9.7,
        //                         "wind_degree":91,
        //                         "wind_dir":"E",
        //                         "pressure_mb":997.0,
        //                         "pressure_in":29.45,
        //                         "precip_mm":0.0,
        //                         "precip_in":0.0,
        //                         "snow_cm":0.0,
        //                         "humidity":53,
        //                         "cloud":20,
        //                         "feelslike_c":34.6,
        //                         "feelslike_f":94.3,
        //                         "windchill_c":31.8,
        //                         "windchill_f":89.2,
        //                         "heatindex_c":35.1,
        //                         "heatindex_f":95.2,
        //                         "dewpoint_c":21.0,
        //                         "dewpoint_f":69.8,
        //                         "will_it_rain":0,
        //                         "chance_of_rain":3,
        //                         "will_it_snow":0,
        //                         "chance_of_snow":0,
        //                         "vis_km":9.9,
        //                         "vis_miles":6.0,
        //                         "gust_mph":9.0,
        //                         "gust_kph":14.4,
        //                         "uv":0,
        //                         "wetbulb_c":24.1,
        //                         "wetbulb_f":75.3,
        //                         "short_rad":0,
        //                         "diff_rad":0,
        //                         "dni":0,
        //                         "gti":0
        //                     },
        //                     {
        //                         "time_epoch":1783373400,
        //                         "time":"2026-07-07 03:00",
        //                         "temp_c":31.7,
        //                         "temp_f":89.1,
        //                         "is_day":0,
        //                         "condition":{
        //                             "text":"Smoky haze",
        //                             "icon":"//cdn.weatherapi.com/weather/64x64/night/149.png",
        //                             "code":1036
        //                         },
        //                         "wind_mph":5.6,
        //                         "wind_kph":9.0,
        //                         "wind_degree":91,
        //                         "wind_dir":"E",
        //                         "pressure_mb":997.0,
        //                         "pressure_in":29.45,
        //                         "precip_mm":0.0,
        //                         "precip_in":0.0,
        //                         "snow_cm":0.0,
        //                         "humidity":53,
        //                         "cloud":26,
        //                         "feelslike_c":34.6,
        //                         "feelslike_f":94.3,
        //                         "windchill_c":31.8,
        //                         "windchill_f":89.2,
        //                         "heatindex_c":35.0,
        //                         "heatindex_f":95.0,
        //                         "dewpoint_c":20.9,
        //                         "dewpoint_f":69.7,
        //                         "will_it_rain":0,
        //                         "chance_of_rain":3,
        //                         "will_it_snow":0,
        //                         "chance_of_snow":0,
        //                         "vis_km":10.0,
        //                         "vis_miles":6.0,
        //                         "gust_mph":8.4,
        //                         "gust_kph":13.6,
        //                         "uv":0,
        //                         "wetbulb_c":24.0,
        //                         "wetbulb_f":75.2,
        //                         "short_rad":0,
        //                         "diff_rad":0,
        //                         "dni":0,
        //                         "gti":0
        //                     },
        //                     {
        //                         "time_epoch":1783377000,
        //                         "time":"2026-07-07 04:00",
        //                         "temp_c":31.6,
        //                         "temp_f":89.0,
        //                         "is_day":0,
        //                         "condition":{
        //                             "text":"Smoky haze",
        //                             "icon":"//cdn.weatherapi.com/weather/64x64/night/149.png",
        //                             "code":1036
        //                         },
        //                         "wind_mph":4.9,
        //                         "wind_kph":7.9,
        //                         "wind_degree":85,
        //                         "wind_dir":"E",
        //                         "pressure_mb":997.0,
        //                         "pressure_in":29.45,
        //                         "precip_mm":0.0,
        //                         "precip_in":0.0,
        //                         "snow_cm":0.0,
        //                         "humidity":53,
        //                         "cloud":46,
        //                         "feelslike_c":34.5,
        //                         "feelslike_f":94.1,
        //                         "windchill_c":31.6,
        //                         "windchill_f":89.0,
        //                         "heatindex_c":34.9,
        //                         "heatindex_f":94.8,
        //                         "dewpoint_c":21.0,
        //                         "dewpoint_f":69.7,
        //                         "will_it_rain":0,
        //                         "chance_of_rain":5,
        //                         "will_it_snow":0,
        //                         "chance_of_snow":0,
        //                         "vis_km":10.0,
        //                         "vis_miles":6.0,
        //                         "gust_mph":7.6,
        //                         "gust_kph":12.2,
        //                         "uv":0,
        //                         "wetbulb_c":24.0,
        //                         "wetbulb_f":75.2,
        //                         "short_rad":0,
        //                         "diff_rad":0,
        //                         "dni":0,
        //                         "gti":0
        //                     },
        //                     {
        //                         "time_epoch":1783380600,
        //                         "time":"2026-07-07 05:00",
        //                         "temp_c":31.4,
        //                         "temp_f":88.6,
        //                         "is_day":0,
        //                         "condition":{
        //                             "text":"Smoky haze",
        //                             "icon":"//cdn.weatherapi.com/weather/64x64/night/149.png",
        //                             "code":1036
        //                         },
        //                         "wind_mph":5.6,
        //                         "wind_kph":9.0,
        //                         "wind_degree":89,
        //                         "wind_dir":"E",
        //                         "pressure_mb":998.0,
        //                         "pressure_in":29.46,
        //                         "precip_mm":0.0,
        //                         "precip_in":0.0,
        //                         "snow_cm":0.0,
        //                         "humidity":54,
        //                         "cloud":44,
        //                         "feelslike_c":34.2,
        //                         "feelslike_f":93.6,
        //                         "windchill_c":31.4,
        //                         "windchill_f":88.6,
        //                         "heatindex_c":34.6,
        //                         "heatindex_f":94.3,
        //                         "dewpoint_c":21.0,
        //                         "dewpoint_f":69.7,
        //                         "will_it_rain":0,
        //                         "chance_of_rain":5,
        //                         "will_it_snow":0,
        //                         "chance_of_snow":0,
        //                         "vis_km":9.7,
        //                         "vis_miles":6.0,
        //                         "gust_mph":8.8,
        //                         "gust_kph":14.2,
        //                         "uv":0,
        //                         "wetbulb_c":23.9,
        //                         "wetbulb_f":75.1,
        //                         "short_rad":0,
        //                         "diff_rad":0,
        //                         "dni":0,
        //                         "gti":0
        //                     },
        //                     {
        //                         "time_epoch":1783384200,
        //                         "time":"2026-07-07 06:00",
        //                         "temp_c":31.9,
        //                         "temp_f":89.5,
        //                         "is_day":1,
        //                         "condition":{
        //                             "text":"Smoky haze",
        //                             "icon":"//cdn.weatherapi.com/weather/64x64/day/149.png",
        //                             "code":1036
        //                         },
        //                         "wind_mph":6.3,
        //                         "wind_kph":10.1,
        //                         "wind_degree":96,
        //                         "wind_dir":"E",
        //                         "pressure_mb":998.0,
        //                         "pressure_in":29.48,
        //                         "precip_mm":0.0,
        //                         "precip_in":0.0,
        //                         "snow_cm":0.0,
        //                         "humidity":53,
        //                         "cloud":90,
        //                         "feelslike_c":34.9,
        //                         "feelslike_f":94.8,
        //                         "windchill_c":31.9,
        //                         "windchill_f":89.5,
        //                         "heatindex_c":35.3,
        //                         "heatindex_f":95.6,
        //                         "dewpoint_c":21.1,
        //                         "dewpoint_f":69.9,
        //                         "will_it_rain":0,
        //                         "chance_of_rain":11,
        //                         "will_it_snow":0,
        //                         "chance_of_snow":0,
        //                         "vis_km":9.6,
        //                         "vis_miles":5.0,
        //                         "gust_mph":9.0,
        //                         "gust_kph":14.5,
        //                         "uv":0.3,
        //                         "wetbulb_c":24.1,
        //                         "wetbulb_f":75.5,
        //                         "short_rad":35.22,
        //                         "diff_rad":18.81,
        //                         "dni":0.57,
        //                         "gti":33.51
        //                     },
        //                     {
        //                         "time_epoch":1783387800,
        //                         "time":"2026-07-07 07:00",
        //                         "temp_c":33.2,
        //                         "temp_f":91.8,
        //                         "is_day":1,
        //                         "condition":{
        //                             "text":"Smoky haze",
        //                             "icon":"//cdn.weatherapi.com/weather/64x64/day/149.png",
        //                             "code":1036
        //                         },
        //                         "wind_mph":7.4,
        //                         "wind_kph":11.9,
        //                         "wind_degree":114,
        //                         "wind_dir":"ESE",
        //                         "pressure_mb":999.0,
        //                         "pressure_in":29.49,
        //                         "precip_mm":0.0,
        //                         "precip_in":0.0,
        //                         "snow_cm":0.0,
        //                         "humidity":50,
        //                         "cloud":97,
        //                         "feelslike_c":36.7,
        //                         "feelslike_f":98.1,
        //                         "windchill_c":33.2,
        //                         "windchill_f":91.8,
        //                         "heatindex_c":37.2,
        //                         "heatindex_f":99.0,
        //                         "dewpoint_c":21.3,
        //                         "dewpoint_f":70.3,
        //                         "will_it_rain":0,
        //                         "chance_of_rain":11,
        //                         "will_it_snow":0,
        //                         "chance_of_snow":0,
        //                         "vis_km":9.0,
        //                         "vis_miles":5.0,
        //                         "gust_mph":9.0,
        //                         "gust_kph":14.5,
        //                         "uv":1.1,
        //                         "wetbulb_c":24.6,
        //                         "wetbulb_f":76.3,
        //                         "short_rad":77.58,
        //                         "diff_rad":40.53,
        //                         "dni":2.77,
        //                         "gti":73.93
        //                     },
        //                     {
        //                         "time_epoch":1783391400,
        //                         "time":"2026-07-07 08:00",
        //                         "temp_c":34.0,
        //                         "temp_f":93.2,
        //                         "is_day":1,
        //                         "condition":{
        //                             "text":"Overcast",
        //                             "icon":"//cdn.weatherapi.com/weather/64x64/day/122.png",
        //                             "code":1009
        //                         },
        //                         "wind_mph":7.6,
        //                         "wind_kph":12.2,
        //                         "wind_degree":117,
        //                         "wind_dir":"ESE",
        //                         "pressure_mb":999.0,
        //                         "pressure_in":29.49,
        //                         "precip_mm":0.0,
        //                         "precip_in":0.0,
        //                         "snow_cm":0.0,
        //                         "humidity":47,
        //                         "cloud":88,
        //                         "feelslike_c":37.6,
        //                         "feelslike_f":99.7,
        //                         "windchill_c":34.0,
        //                         "windchill_f":93.2,
        //                         "heatindex_c":38.2,
        //                         "heatindex_f":100.8,
        //                         "dewpoint_c":21.3,
        //                         "dewpoint_f":70.3,
        //                         "will_it_rain":0,
        //                         "chance_of_rain":9,
        //                         "will_it_snow":0,
        //                         "chance_of_snow":0,
        //                         "vis_km":10.0,
        //                         "vis_miles":6.0,
        //                         "gust_mph":9.0,
        //                         "gust_kph":14.5,
        //                         "uv":2.8,
        //                         "wetbulb_c":24.8,
        //                         "wetbulb_f":76.7,
        //                         "short_rad":109.41,
        //                         "diff_rad":59.63,
        //                         "dni":5.51,
        //                         "gti":104.4
        //                     },
        //                     {
        //                         "time_epoch":1783395000,
        //                         "time":"2026-07-07 09:00",
        //                         "temp_c":35.0,
        //                         "temp_f":95.1,
        //                         "is_day":1,
        //                         "condition":{
        //                             "text":"Overcast",
        //                             "icon":"//cdn.weatherapi.com/weather/64x64/day/122.png",
        //                             "code":1009
        //                         },
        //                         "wind_mph":6.0,
        //                         "wind_kph":9.7,
        //                         "wind_degree":133,
        //                         "wind_dir":"SE",
        //                         "pressure_mb":999.0,
        //                         "pressure_in":29.49,
        //                         "precip_mm":0.0,
        //                         "precip_in":0.0,
        //                         "snow_cm":0.0,
        //                         "humidity":45,
        //                         "cloud":93,
        //                         "feelslike_c":38.8,
        //                         "feelslike_f":101.8,
        //                         "windchill_c":35.0,
        //                         "windchill_f":95.1,
        //                         "heatindex_c":39.5,
        //                         "heatindex_f":103.1,
        //                         "dewpoint_c":21.2,
        //                         "dewpoint_f":70.2,
        //                         "will_it_rain":0,
        //                         "chance_of_rain":9,
        //                         "will_it_snow":0,
        //                         "chance_of_snow":0,
        //                         "vis_km":10.0,
        //                         "vis_miles":6.0,
        //                         "gust_mph":7.0,
        //                         "gust_kph":11.2,
        //                         "uv":5.0,
        //                         "wetbulb_c":25.1,
        //                         "wetbulb_f":77.1,
        //                         "short_rad":158.94,
        //                         "diff_rad":87.69,
        //                         "dni":25.17,
        //                         "gti":153.14
        //                     },
        //                     {
        //                         "time_epoch":1783398600,
        //                         "time":"2026-07-07 10:00",
        //                         "temp_c":35.8,
        //                         "temp_f":96.5,
        //                         "is_day":1,
        //                         "condition":{
        //                             "text":"Partly Cloudy",
        //                             "icon":"//cdn.weatherapi.com/weather/64x64/day/116.png",
        //                             "code":1003
        //                         },
        //                         "wind_mph":4.0,
        //                         "wind_kph":6.5,
        //                         "wind_degree":165,
        //                         "wind_dir":"SSE",
        //                         "pressure_mb":998.0,
        //                         "pressure_in":29.48,
        //                         "precip_mm":0.0,
        //                         "precip_in":0.0,
        //                         "snow_cm":0.0,
        //                         "humidity":43,
        //                         "cloud":37,
        //                         "feelslike_c":39.7,
        //                         "feelslike_f":103.5,
        //                         "windchill_c":35.8,
        //                         "windchill_f":96.5,
        //                         "heatindex_c":40.4,
        //                         "heatindex_f":104.8,
        //                         "dewpoint_c":21.1,
        //                         "dewpoint_f":70.0,
        //                         "will_it_rain":0,
        //                         "chance_of_rain":3,
        //                         "will_it_snow":0,
        //                         "chance_of_snow":0,
        //                         "vis_km":10.0,
        //                         "vis_miles":6.0,
        //                         "gust_mph":4.6,
        //                         "gust_kph":7.5,
        //                         "uv":5.3,
        //                         "wetbulb_c":25.2,
        //                         "wetbulb_f":77.4,
        //                         "short_rad":207.17,
        //                         "diff_rad":113.22,
        //                         "dni":92.51,
        //                         "gti":204.73
        //                     },
        //                     {
        //                         "time_epoch":1783402200,
        //                         "time":"2026-07-07 11:00",
        //                         "temp_c":36.8,
        //                         "temp_f":98.3,
        //                         "is_day":1,
        //                         "condition":{
        //                             "text":"Partly Cloudy",
        //                             "icon":"//cdn.weatherapi.com/weather/64x64/day/116.png",
        //                             "code":1003
        //                         },
        //                         "wind_mph":4.5,
        //                         "wind_kph":7.2,
        //                         "wind_degree":233,
        //                         "wind_dir":"SW",
        //                         "pressure_mb":998.0,
        //                         "pressure_in":29.46,
        //                         "precip_mm":0.0,
        //                         "precip_in":0.0,
        //                         "snow_cm":0.0,
        //                         "humidity":40,
        //                         "cloud":28,
        //                         "feelslike_c":31.4,
        //                         "feelslike_f":88.5,
        //                         "windchill_c":36.8,
        //                         "windchill_f":98.3,
        //                         "heatindex_c":41.6,
        //                         "heatindex_f":106.9,
        //                         "dewpoint_c":21.0,
        //                         "dewpoint_f":69.7,
        //                         "will_it_rain":0,
        //                         "chance_of_rain":2,
        //                         "will_it_snow":0,
        //                         "chance_of_snow":0,
        //                         "vis_km":10.0,
        //                         "vis_miles":6.0,
        //                         "gust_mph":5.1,
        //                         "gust_kph":8.3,
        //                         "uv":3.3,
        //                         "wetbulb_c":25.4,
        //                         "wetbulb_f":77.6,
        //                         "short_rad":262.62,
        //                         "diff_rad":141.21,
        //                         "dni":257.24,
        //                         "gti":271.55
        //                     },
        //                     {
        //                         "time_epoch":1783405800,
        //                         "time":"2026-07-07 12:00",
        //                         "temp_c":37.6,
        //                         "temp_f":99.7,
        //                         "is_day":1,
        //                         "condition":{
        //                             "text":"Sunny",
        //                             "icon":"//cdn.weatherapi.com/weather/64x64/day/113.png",
        //                             "code":1000
        //                         },
        //                         "wind_mph":6.9,
        //                         "wind_kph":11.2,
        //                         "wind_degree":246,
        //                         "wind_dir":"WSW",
        //                         "pressure_mb":997.0,
        //                         "pressure_in":29.44,
        //                         "precip_mm":0.0,
        //                         "precip_in":0.0,
        //                         "snow_cm":0.0,
        //                         "humidity":38,
        //                         "cloud":22,
        //                         "feelslike_c":31.4,
        //                         "feelslike_f":88.5,
        //                         "windchill_c":37.6,
        //                         "windchill_f":99.7,
        //                         "heatindex_c":42.5,
        //                         "heatindex_f":108.4,
        //                         "dewpoint_c":20.8,
        //                         "dewpoint_f":69.5,
        //                         "will_it_rain":0,
        //                         "chance_of_rain":2,
        //                         "will_it_snow":0,
        //                         "chance_of_snow":0,
        //                         "vis_km":10.0,
        //                         "vis_miles":6.0,
        //                         "gust_mph":8.0,
        //                         "gust_kph":12.9,
        //                         "uv":2.9,
        //                         "wetbulb_c":25.5,
        //                         "wetbulb_f":77.9,
        //                         "short_rad":588.84,
        //                         "diff_rad":246.64,
        //                         "dni":0.0,
        //                         "gti":0.0
        //                     },
        //                     {
        //                         "time_epoch":1783409400,
        //                         "time":"2026-07-07 13:00",
        //                         "temp_c":35.1,
        //                         "temp_f":95.2,
        //                         "is_day":1,
        //                         "condition":{
        //                             "text":"Moderate or heavy rain with thunder",
        //                             "icon":"//cdn.weatherapi.com/weather/64x64/day/389.png",
        //                             "code":1276
        //                         },
        //                         "wind_mph":5.6,
        //                         "wind_kph":9.0,
        //                         "wind_degree":232,
        //                         "wind_dir":"SW",
        //                         "pressure_mb":999.0,
        //                         "pressure_in":29.5,
        //                         "precip_mm":0.0,
        //                         "precip_in":0.0,
        //                         "snow_cm":0.0,
        //                         "humidity":56,
        //                         "cloud":75,
        //                         "feelslike_c":37.2,
        //                         "feelslike_f":99.0,
        //                         "windchill_c":38.1,
        //                         "windchill_f":100.5,
        //                         "heatindex_c":42.9,
        //                         "heatindex_f":109.2,
        //                         "dewpoint_c":20.7,
        //                         "dewpoint_f":69.2,
        //                         "will_it_rain":0,
        //                         "chance_of_rain":3,
        //                         "will_it_snow":0,
        //                         "chance_of_snow":0,
        //                         "vis_km":4.0,
        //                         "vis_miles":2.0,
        //                         "gust_mph":6.4,
        //                         "gust_kph":10.4,
        //                         "uv":2.7,
        //                         "wetbulb_c":25.5,
        //                         "wetbulb_f":77.9,
        //                         "short_rad":625.14,
        //                         "diff_rad":212.99,
        //                         "dni":0.0,
        //                         "gti":0.0
        //                     },
        //                     {
        //                         "time_epoch":1783413000,
        //                         "time":"2026-07-07 14:00",
        //                         "temp_c":38.2,
        //                         "temp_f":100.7,
        //                         "is_day":1,
        //                         "condition":{
        //                             "text":"Patchy rain nearby",
        //                             "icon":"//cdn.weatherapi.com/weather/64x64/day/176.png",
        //                             "code":1063
        //                         },
        //                         "wind_mph":2.9,
        //                         "wind_kph":4.7,
        //                         "wind_degree":114,
        //                         "wind_dir":"ESE",
        //                         "pressure_mb":995.0,
        //                         "pressure_in":29.4,
        //                         "precip_mm":0.01,
        //                         "precip_in":0.0,
        //                         "snow_cm":0.0,
        //                         "humidity":37,
        //                         "cloud":80,
        //                         "feelslike_c":33.3,
        //                         "feelslike_f":91.9,
        //                         "windchill_c":38.2,
        //                         "windchill_f":100.7,
        //                         "heatindex_c":43.1,
        //                         "heatindex_f":109.6,
        //                         "dewpoint_c":20.7,
        //                         "dewpoint_f":69.3,
        //                         "will_it_rain":0,
        //                         "chance_of_rain":7,
        //                         "will_it_snow":0,
        //                         "chance_of_snow":0,
        //                         "vis_km":10.0,
        //                         "vis_miles":6.0,
        //                         "gust_mph":3.4,
        //                         "gust_kph":5.4,
        //                         "uv":2.7,
        //                         "wetbulb_c":25.6,
        //                         "wetbulb_f":78.0,
        //                         "short_rad":610.74,
        //                         "diff_rad":182.4,
        //                         "dni":0.0,
        //                         "gti":0.0
        //                     },
        //                     {
        //                         "time_epoch":1783416600,
        //                         "time":"2026-07-07 15:00",
        //                         "temp_c":36.4,
        //                         "temp_f":97.5,
        //                         "is_day":1,
        //                         "condition":{
        //                             "text":"Partly Cloudy",
        //                             "icon":"//cdn.weatherapi.com/weather/64x64/day/116.png",
        //                             "code":1003
        //                         },
        //                         "wind_mph":8.3,
        //                         "wind_kph":13.3,
        //                         "wind_degree":78,
        //                         "wind_dir":"ENE",
        //                         "pressure_mb":995.0,
        //                         "pressure_in":29.39,
        //                         "precip_mm":0.0,
        //                         "precip_in":0.0,
        //                         "snow_cm":0.0,
        //                         "humidity":41,
        //                         "cloud":48,
        //                         "feelslike_c":40.2,
        //                         "feelslike_f":104.4,
        //                         "windchill_c":36.4,
        //                         "windchill_f":97.5,
        //                         "heatindex_c":41.0,
        //                         "heatindex_f":105.7,
        //                         "dewpoint_c":20.9,
        //                         "dewpoint_f":69.7,
        //                         "will_it_rain":0,
        //                         "chance_of_rain":4,
        //                         "will_it_snow":0,
        //                         "chance_of_snow":0,
        //                         "vis_km":10.0,
        //                         "vis_miles":6.0,
        //                         "gust_mph":10.4,
        //                         "gust_kph":16.8,
        //                         "uv":2.9,
        //                         "wetbulb_c":25.2,
        //                         "wetbulb_f":77.4,
        //                         "short_rad":485.5,
        //                         "diff_rad":153.98,
        //                         "dni":1054.32,
        //                         "gti":551.69
        //                     },
        //                     {
        //                         "time_epoch":1783420200,
        //                         "time":"2026-07-07 16:00",
        //                         "temp_c":36.8,
        //                         "temp_f":98.2,
        //                         "is_day":1,
        //                         "condition":{
        //                             "text":"Sunny",
        //                             "icon":"//cdn.weatherapi.com/weather/64x64/day/113.png",
        //                             "code":1000
        //                         },
        //                         "wind_mph":8.5,
        //                         "wind_kph":13.7,
        //                         "wind_degree":80,
        //                         "wind_dir":"E",
        //                         "pressure_mb":994.0,
        //                         "pressure_in":29.37,
        //                         "precip_mm":0.0,
        //                         "precip_in":0.0,
        //                         "snow_cm":0.0,
        //                         "humidity":40,
        //                         "cloud":23,
        //                         "feelslike_c":40.8,
        //                         "feelslike_f":105.4,
        //                         "windchill_c":36.8,
        //                         "windchill_f":98.2,
        //                         "heatindex_c":41.6,
        //                         "heatindex_f":106.9,
        //                         "dewpoint_c":21.0,
        //                         "dewpoint_f":69.9,
        //                         "will_it_rain":0,
        //                         "chance_of_rain":2,
        //                         "will_it_snow":0,
        //                         "chance_of_snow":0,
        //                         "vis_km":10.0,
        //                         "vis_miles":6.0,
        //                         "gust_mph":10.0,
        //                         "gust_kph":16.1,
        //                         "uv":2.0,
        //                         "wetbulb_c":25.4,
        //                         "wetbulb_f":77.7,
        //                         "short_rad":463.22,
        //                         "diff_rad":151.55,
        //                         "dni":1005.94,
        //                         "gti":526.38
        //                     },
        //                     {
        //                         "time_epoch":1783423800,
        //                         "time":"2026-07-07 17:00",
        //                         "temp_c":37.5,
        //                         "temp_f":99.5,
        //                         "is_day":1,
        //                         "condition":{
        //                             "text":"Sunny",
        //                             "icon":"//cdn.weatherapi.com/weather/64x64/day/113.png",
        //                             "code":1000
        //                         },
        //                         "wind_mph":7.2,
        //                         "wind_kph":11.5,
        //                         "wind_degree":87,
        //                         "wind_dir":"E",
        //                         "pressure_mb":994.0,
        //                         "pressure_in":29.35,
        //                         "precip_mm":0.0,
        //                         "precip_in":0.0,
        //                         "snow_cm":0.0,
        //                         "humidity":38,
        //                         "cloud":20,
        //                         "feelslike_c":31.3,
        //                         "feelslike_f":88.3,
        //                         "windchill_c":37.5,
        //                         "windchill_f":99.5,
        //                         "heatindex_c":42.3,
        //                         "heatindex_f":108.2,
        //                         "dewpoint_c":20.8,
        //                         "dewpoint_f":69.4,
        //                         "will_it_rain":0,
        //                         "chance_of_rain":2,
        //                         "will_it_snow":0,
        //                         "chance_of_snow":0,
        //                         "vis_km":10.0,
        //                         "vis_miles":6.0,
        //                         "gust_mph":8.3,
        //                         "gust_kph":13.4,
        //                         "uv":0.8,
        //                         "wetbulb_c":25.4,
        //                         "wetbulb_f":77.8,
        //                         "short_rad":444.82,
        //                         "diff_rad":145.74,
        //                         "dni":965.97,
        //                         "gti":505.46
        //                     },
        //                     {
        //                         "time_epoch":1783427400,
        //                         "time":"2026-07-07 18:00",
        //                         "temp_c":37.1,
        //                         "temp_f":98.7,
        //                         "is_day":1,
        //                         "condition":{
        //                             "text":"Sunny",
        //                             "icon":"//cdn.weatherapi.com/weather/64x64/day/113.png",
        //                             "code":1000
        //                         },
        //                         "wind_mph":5.1,
        //                         "wind_kph":8.3,
        //                         "wind_degree":103,
        //                         "wind_dir":"ESE",
        //                         "pressure_mb":993.0,
        //                         "pressure_in":29.33,
        //                         "precip_mm":0.0,
        //                         "precip_in":0.0,
        //                         "snow_cm":0.0,
        //                         "humidity":39,
        //                         "cloud":23,
        //                         "feelslike_c":31.4,
        //                         "feelslike_f":88.5,
        //                         "windchill_c":37.1,
        //                         "windchill_f":98.7,
        //                         "heatindex_c":41.6,
        //                         "heatindex_f":106.9,
        //                         "dewpoint_c":20.7,
        //                         "dewpoint_f":69.2,
        //                         "will_it_rain":0,
        //                         "chance_of_rain":2,
        //                         "will_it_snow":0,
        //                         "chance_of_snow":0,
        //                         "vis_km":10.0,
        //                         "vis_miles":6.0,
        //                         "gust_mph":6.5,
        //                         "gust_kph":10.4,
        //                         "uv":0.2,
        //                         "wetbulb_c":25.2,
        //                         "wetbulb_f":77.4,
        //                         "short_rad":166.68,
        //                         "diff_rad":66.54,
        //                         "dni":32.0,
        //                         "gti":161.08
        //                     },
        //                     {
        //                         "time_epoch":1783431000,
        //                         "time":"2026-07-07 19:00",
        //                         "temp_c":35.9,
        //                         "temp_f":96.6,
        //                         "is_day":0,
        //                         "condition":{
        //                             "text":"Clear",
        //                             "icon":"//cdn.weatherapi.com/weather/64x64/night/113.png",
        //                             "code":1000
        //                         },
        //                         "wind_mph":4.7,
        //                         "wind_kph":7.6,
        //                         "wind_degree":129,
        //                         "wind_dir":"SE",
        //                         "pressure_mb":994.0,
        //                         "pressure_in":29.34,
        //                         "precip_mm":0.0,
        //                         "precip_in":0.0,
        //                         "snow_cm":0.0,
        //                         "humidity":42,
        //                         "cloud":22,
        //                         "feelslike_c":39.5,
        //                         "feelslike_f":103.1,
        //                         "windchill_c":35.9,
        //                         "windchill_f":96.6,
        //                         "heatindex_c":40.3,
        //                         "heatindex_f":104.5,
        //                         "dewpoint_c":20.8,
        //                         "dewpoint_f":69.5,
        //                         "will_it_rain":0,
        //                         "chance_of_rain":2,
        //                         "will_it_snow":0,
        //                         "chance_of_snow":0,
        //                         "vis_km":8.2,
        //                         "vis_miles":5.0,
        //                         "gust_mph":7.1,
        //                         "gust_kph":11.4,
        //                         "uv":0,
        //                         "wetbulb_c":25.0,
        //                         "wetbulb_f":77.1,
        //                         "short_rad":0,
        //                         "diff_rad":0,
        //                         "dni":0,
        //                         "gti":0
        //                     },
        //                     {
        //                         "time_epoch":1783434600,
        //                         "time":"2026-07-07 20:00",
        //                         "temp_c":35.5,
        //                         "temp_f":95.8,
        //                         "is_day":0,
        //                         "condition":{
        //                             "text":"Clear",
        //                             "icon":"//cdn.weatherapi.com/weather/64x64/night/113.png",
        //                             "code":1000
        //                         },
        //                         "wind_mph":4.9,
        //                         "wind_kph":7.9,
        //                         "wind_degree":141,
        //                         "wind_dir":"SE",
        //                         "pressure_mb":994.0,
        //                         "pressure_in":29.36,
        //                         "precip_mm":0.0,
        //                         "precip_in":0.0,
        //                         "snow_cm":0.0,
        //                         "humidity":43,
        //                         "cloud":23,
        //                         "feelslike_c":39.1,
        //                         "feelslike_f":102.4,
        //                         "windchill_c":35.5,
        //                         "windchill_f":95.8,
        //                         "heatindex_c":39.8,
        //                         "heatindex_f":103.6,
        //                         "dewpoint_c":20.9,
        //                         "dewpoint_f":69.7,
        //                         "will_it_rain":0,
        //                         "chance_of_rain":2,
        //                         "will_it_snow":0,
        //                         "chance_of_snow":0,
        //                         "vis_km":7.1,
        //                         "vis_miles":4.0,
        //                         "gust_mph":7.8,
        //                         "gust_kph":12.6,
        //                         "uv":0,
        //                         "wetbulb_c":25.0,
        //                         "wetbulb_f":77.0,
        //                         "short_rad":0,
        //                         "diff_rad":0,
        //                         "dni":0,
        //                         "gti":0
        //                     },
        //                     {
        //                         "time_epoch":1783438200,
        //                         "time":"2026-07-07 21:00",
        //                         "temp_c":35.2,
        //                         "temp_f":95.3,
        //                         "is_day":0,
        //                         "condition":{
        //                             "text":"Smog",
        //                             "icon":"//cdn.weatherapi.com/weather/64x64/night/152.png",
        //                             "code":1039
        //                         },
        //                         "wind_mph":5.1,
        //                         "wind_kph":8.3,
        //                         "wind_degree":147,
        //                         "wind_dir":"SSE",
        //                         "pressure_mb":995.0,
        //                         "pressure_in":29.38,
        //                         "precip_mm":0.0,
        //                         "precip_in":0.0,
        //                         "snow_cm":0.0,
        //                         "humidity":44,
        //                         "cloud":42,
        //                         "feelslike_c":38.8,
        //                         "feelslike_f":101.8,
        //                         "windchill_c":35.2,
        //                         "windchill_f":95.3,
        //                         "heatindex_c":39.5,
        //                         "heatindex_f":103.2,
        //                         "dewpoint_c":21.1,
        //                         "dewpoint_f":69.9,
        //                         "will_it_rain":0,
        //                         "chance_of_rain":4,
        //                         "will_it_snow":0,
        //                         "chance_of_snow":0,
        //                         "vis_km":6.7,
        //                         "vis_miles":4.0,
        //                         "gust_mph":8.2,
        //                         "gust_kph":13.2,
        //                         "uv":0,
        //                         "wetbulb_c":25.0,
        //                         "wetbulb_f":77.0,
        //                         "short_rad":0,
        //                         "diff_rad":0,
        //                         "dni":0,
        //                         "gti":0
        //                     },
        //                     {
        //                         "time_epoch":1783441800,
        //                         "time":"2026-07-07 22:00",
        //                         "temp_c":34.8,
        //                         "temp_f":94.6,
        //                         "is_day":0,
        //                         "condition":{
        //                             "text":"Partly Cloudy",
        //                             "icon":"//cdn.weatherapi.com/weather/64x64/night/116.png",
        //                             "code":1003
        //                         },
        //                         "wind_mph":7.4,
        //                         "wind_kph":11.9,
        //                         "wind_degree":152,
        //                         "wind_dir":"SSE",
        //                         "pressure_mb":996.0,
        //                         "pressure_in":29.4,
        //                         "precip_mm":0.0,
        //                         "precip_in":0.0,
        //                         "snow_cm":0.0,
        //                         "humidity":45,
        //                         "cloud":44,
        //                         "feelslike_c":38.6,
        //                         "feelslike_f":101.5,
        //                         "windchill_c":34.8,
        //                         "windchill_f":94.6,
        //                         "heatindex_c":39.2,
        //                         "heatindex_f":102.6,
        //                         "dewpoint_c":21.3,
        //                         "dewpoint_f":70.3,
        //                         "will_it_rain":0,
        //                         "chance_of_rain":4,
        //                         "will_it_snow":0,
        //                         "chance_of_snow":0,
        //                         "vis_km":6.5,
        //                         "vis_miles":4.0,
        //                         "gust_mph":11.5,
        //                         "gust_kph":18.5,
        //                         "uv":0,
        //                         "wetbulb_c":25.0,
        //                         "wetbulb_f":77.0,
        //                         "short_rad":0,
        //                         "diff_rad":0,
        //                         "dni":0,
        //                         "gti":0
        //                     },
        //                     {
        //                         "time_epoch":1783445400,
        //                         "time":"2026-07-07 23:00",
        //                         "temp_c":34.4,
        //                         "temp_f":93.9,
        //                         "is_day":0,
        //                         "condition":{
        //                             "text":"Partly Cloudy",
        //                             "icon":"//cdn.weatherapi.com/weather/64x64/night/116.png",
        //                             "code":1003
        //                         },
        //                         "wind_mph":8.1,
        //                         "wind_kph":13.0,
        //                         "wind_degree":165,
        //                         "wind_dir":"SSE",
        //                         "pressure_mb":996.0,
        //                         "pressure_in":29.4,
        //                         "precip_mm":0.0,
        //                         "precip_in":0.0,
        //                         "snow_cm":0.0,
        //                         "humidity":47,
        //                         "cloud":60,
        //                         "feelslike_c":38.1,
        //                         "feelslike_f":100.6,
        //                         "windchill_c":34.4,
        //                         "windchill_f":93.9,
        //                         "heatindex_c":38.8,
        //                         "heatindex_f":101.8,
        //                         "dewpoint_c":21.4,
        //                         "dewpoint_f":70.4,
        //                         "will_it_rain":0,
        //                         "chance_of_rain":5,
        //                         "will_it_snow":0,
        //                         "chance_of_snow":0,
        //                         "vis_km":6.7,
        //                         "vis_miles":4.0,
        //                         "gust_mph":12.0,
        //                         "gust_kph":19.3,
        //                         "uv":0,
        //                         "wetbulb_c":25.0,
        //                         "wetbulb_f":76.9,
        //                         "short_rad":0,
        //                         "diff_rad":0,
        //                         "dni":0,
        //                         "gti":0
        //                     }
        //                 ]
        //             },
        //             {
        //                 "date":"2026-07-09",
        //                 "date_epoch":1783555200,
        //                 "day":{
        //                     "maxtemp_c":38.4,
        //                     "maxtemp_f":101.1,
        //                     "mintemp_c":29.0,
        //                     "mintemp_f":84.2,
        //                     "avgtemp_c":32.8,
        //                     "avgtemp_f":91.0,
        //                     "maxwind_mph":10.1,
        //                     "maxwind_kph":16.2,
        //                     "totalprecip_mm":6.93,
        //                     "totalprecip_in":0.27,
        //                     "totalsnow_cm":0.0,
        //                     "avgvis_km":8.8,
        //                     "avgvis_miles":5.0,
        //                     "avghumidity":58,
        //                     "daily_will_it_rain":0,
        //                     "daily_chance_of_rain":66,
        //                     "daily_will_it_snow":0,
        //                     "daily_chance_of_snow":0,
        //                     "condition":{
        //                         "text":"Partly Cloudy",
        //                         "icon":"//cdn.weatherapi.com/weather/64x64/day/116.png",
        //                         "code":1003
        //                     },
        //                     "uv":11.2
        //                 },
        //                 "astro":{
        //                     "sunrise":"05:30 AM",
        //                     "sunset":"07:24 PM",
        //                     "moonrise":"12:19 AM",
        //                     "moonset":"01:58 PM",
        //                     "moon_phase":"Waning Crescent",
        //                     "moon_illumination":19,
        //                     "is_moon_up":1,
        //                     "is_sun_up":1
        //                 }
        //             },
        //             {
        //                 "date":"2026-07-10",
        //                 "date_epoch":1783641600,
        //                 "day":{
        //                     "maxtemp_c":37.6,
        //                     "maxtemp_f":99.6,
        //                     "mintemp_c":29.2,
        //                     "mintemp_f":84.6,
        //                     "avgtemp_c":32.5,
        //                     "avgtemp_f":90.5,
        //                     "maxwind_mph":8.9,
        //                     "maxwind_kph":14.4,
        //                     "totalprecip_mm":12.51,
        //                     "totalprecip_in":0.49,
        //                     "totalsnow_cm":0.0,
        //                     "avgvis_km":9.5,
        //                     "avgvis_miles":5.0,
        //                     "avghumidity":62,
        //                     "daily_will_it_rain":1,
        //                     "daily_chance_of_rain":73,
        //                     "daily_will_it_snow":0,
        //                     "daily_chance_of_snow":0,
        //                     "condition":{
        //                         "text":"Patchy rain nearby",
        //                         "icon":"//cdn.weatherapi.com/weather/64x64/day/176.png",
        //                         "code":1063
        //                     },
        //                     "uv":10.2
        //                 },
        //                 "astro":{
        //                     "sunrise":"05:30 AM",
        //                     "sunset":"07:23 PM",
        //                     "moonrise":"12:55 AM",
        //                     "moonset":"03:03 PM",
        //                     "moon_phase":"Waning Crescent",
        //                     "moon_illumination":12,
        //                     "is_moon_up":1,
        //                     "is_sun_up":1
        //                 }
        //             },
        //             {
        //                 "date":"2026-07-11",
        //                 "date_epoch":1783728000,
        //                 "day":{
        //                     "maxtemp_c":40.4,
        //                     "maxtemp_f":104.8,
        //                     "mintemp_c":29.3,
        //                     "mintemp_f":84.7,
        //                     "avgtemp_c":34.7,
        //                     "avgtemp_f":94.5,
        //                     "maxwind_mph":13.6,
        //                     "maxwind_kph":22.0,
        //                     "totalprecip_mm":0.48,
        //                     "totalprecip_in":0.02,
        //                     "totalsnow_cm":0.0,
        //                     "avgvis_km":7.7,
        //                     "avgvis_miles":4.0,
        //                     "avghumidity":49,
        //                     "daily_will_it_rain":0,
        //                     "daily_chance_of_rain":36,
        //                     "daily_will_it_snow":0,
        //                     "daily_chance_of_snow":0,
        //                     "condition":{
        //                         "text":"Partly Cloudy",
        //                         "icon":"//cdn.weatherapi.com/weather/64x64/day/116.png",
        //                         "code":1003
        //                     },
        //                     "uv":10.0
        //                 },
        //                 "astro":{
        //                     "sunrise":"05:31 AM",
        //                     "sunset":"07:23 PM",
        //                     "moonrise":"01:37 AM",
        //                     "moonset":"04:11 PM",
        //                     "moon_phase":"Waning Crescent",
        //                     "moon_illumination":6,
        //                     "is_moon_up":1,
        //                     "is_sun_up":1
        //                 }
        //             },
        //             {
        //                 "date":"2026-07-12",
        //                 "date_epoch":1783814400,
        //                 "day":{
        //                     "maxtemp_c":41.4,
        //                     "maxtemp_f":106.5,
        //                     "mintemp_c":29.7,
        //                     "mintemp_f":85.5,
        //                     "avgtemp_c":35.8,
        //                     "avgtemp_f":96.4,
        //                     "maxwind_mph":14.8,
        //                     "maxwind_kph":23.8,
        //                     "totalprecip_mm":0.28,
        //                     "totalprecip_in":0.01,
        //                     "totalsnow_cm":0.0,
        //                     "avgvis_km":10.0,
        //                     "avgvis_miles":6.0,
        //                     "avghumidity":44,
        //                     "daily_will_it_rain":0,
        //                     "daily_chance_of_rain":17,
        //                     "daily_will_it_snow":0,
        //                     "daily_chance_of_snow":0,
        //                     "condition":{
        //                         "text":"Sunny",
        //                         "icon":"//cdn.weatherapi.com/weather/64x64/day/113.png",
        //                         "code":1000
        //                     },
        //                     "uv":10.0
        //                 },
        //                 "astro":{
        //                     "sunrise":"05:31 AM",
        //                     "sunset":"07:23 PM",
        //                     "moonrise":"02:29 AM",
        //                     "moonset":"05:20 PM",
        //                     "moon_phase":"New Moon",
        //                     "moon_illumination":2,
        //                     "is_moon_up":1,
        //                     "is_sun_up":1
        //                 }
        //             },
        //             {
        //                 "date":"2026-07-13",
        //                 "date_epoch":1783900800,
        //                 "day":{
        //                     "maxtemp_c":40.7,
        //                     "maxtemp_f":105.2,
        //                     "mintemp_c":28.5,
        //                     "mintemp_f":83.3,
        //                     "avgtemp_c":34.1,
        //                     "avgtemp_f":93.3,
        //                     "maxwind_mph":13.6,
        //                     "maxwind_kph":22.0,
        //                     "totalprecip_mm":0.0,
        //                     "totalprecip_in":0.0,
        //                     "totalsnow_cm":0.0,
        //                     "avgvis_km":10.0,
        //                     "avgvis_miles":6.0,
        //                     "avghumidity":55,
        //                     "daily_will_it_rain":0,
        //                     "daily_chance_of_rain":3,
        //                     "daily_will_it_snow":0,
        //                     "daily_chance_of_snow":0,
        //                     "condition":{
        //                         "text":"Sunny",
        //                         "icon":"//cdn.weatherapi.com/weather/64x64/day/113.png",
        //                         "code":1000
        //                     },
        //                     "uv":10.0
        //                 },
        //                 "astro":{
        //                     "sunrise":"05:32 AM",
        //                     "sunset":"07:23 PM",
        //                     "moonrise":"03:31 AM",
        //                     "moonset":"06:25 PM",
        //                     "moon_phase":"New Moon",
        //                     "moon_illumination":0,
        //                     "is_moon_up":1,
        //                     "is_sun_up":1
        //                 }
        //             }
        //         ]
        //     }
        // }

        const result = await fetch(
            "https://api.weatherapi.com/v1/forecast.json?" +
            `q=${lat},${lng}&` +
            `days=${days || 5}&` +
            "alerts=no&" +
            `aqi=${aqi || "no"}&` +
            `tp=${timePeriod || 90}&` +
            `key=${WEATHER_API_KEY}`
        )
        const rawData = await result.json();

        // Validates the structural footprint safely
        const validation = weatherForecastApiSchema.safeParse(rawData);

        if (!validation.success) {
            console.error("API Schema changed or is invalid:", validation.error);
            return []; // Return fallback safe state
        }

        // Success! TypeScript now recognizes this as ForecastData[]
        const validatedData = validation.data;
        return validatedData;

    } catch (error) {
        console.error("Network or parsing error:", error);
        return [];
    }
}

type SearchLocationArgsType = {
    city?: string
    region?: string
    state?: string
    country?: string

}

export async function searchLocation({city, region, state, country}: SearchLocationArgsType) {

    try {

        const location: string | undefined = city || region || state || country;
        if (!location) {
            throw new Error("No location found.");
        }

        const result = await fetch(
            "https://api.weatherapi.com/v1/search.json?" +
            `q=${location}&` +
            `key=${WEATHER_API_KEY}`
        )
        const rawData = await result.json();

        // Validates the structural footprint safely
        const validation = searchLocationApiSchema.safeParse(rawData);

        if (!validation.success) {
            console.error("API Schema changed or is invalid:", validation.error);
            return []; // Return fallback safe state
        }

        // Success! TypeScript now recognizes this as LocationSearchResult[]
        const validatedData = validation.data;
        return validatedData;

    } catch (error) {
        console.error("Network or parsing error:", error);
        return [];
    }

}